baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Example website'
theme = 'puppet'

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = -1
[[menu.main]]
identifier = "team"
name = "Team"
url = "/team/"
weight = -1
[[menu.main]]
identifier = "capabilities"
name = "Capabilities"
url = "/capabilities/"
weight = -1